global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 2s
  group_interval: 5s
  repeat_interval: 1m
  receiver: 'sentinelgraph-webhook'

receivers:
- name: 'sentinelgraph-webhook'
  webhook_configs:
  - url: 'http://host.docker.internal:8001/api/v1/alerts'
    send_resolved: true
