version: '3.8'

services:
  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8011:8011"
    networks:
      - sentinel-net

  order-service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8012:8012"
    environment:
      - USER_SERVICE_URL=http://user-service:8011
      - PAYMENT_SERVICE_URL=http://payment-service:8013
    depends_on:
      - user-service
      - payment-service
    networks:
      - sentinel-net

  payment-service:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8013:8013"
    networks:
      - sentinel-net

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - user-service
      - order-service
      - payment-service
    networks:
      - sentinel-net

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge
